image: ruby:2.3

services:
  - postgres:latest

variables:
  POSTGRES_DB: lost_items_test
  POSTGRES_USER: lost_items
  POSTGRES_PASSWORD: "test"

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - gem install bundler --no-ri --no-rdoc
  - cp config/database.gitlab-ci.yml config/database.yml
  - touch log/application.log
  - touch log/test.log
  - rm Gemfile.lock
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - bundle exec rake db:drop RAILS_ENV=test
  - bundle exec rake db:create RAILS_ENV=test

minitest:
  script:
    - bundle exec rake
